### ISSUE TITLE
NavigableSubMap.is_empty is calling an underlying 'is_emptry' method which clearly does not exist.

### ISSUE THREAD

**Issue by rafaelsilverioit** [GavinPHR/pytreemap#1]
I'm using the latest version provided by pip (pytreemap==0.4). The problematic line is:

```python
    def is_empty(self):
        return (self.m.is_emptry()
                if self.from_start and self.to_end
                else self.entry_set().is_emptry())
```

It is still in there as you can see: https://github.com/GavinPHR/pytreemap/blob/master/pytreemap/tree_map_inner_class/navigable_sub_map.py#L146

If you are not willing to correct, I may do it if you are open to accept PRs.

**Comment by GavinPHR** [comment]
Hi, thanks for the issue. My plate is quite full right now, will certainly take a look if you can submit a PR.

**Comment by rafaelsilverioit** [comment]
Hi @GavinPHR! I've created 2 PRs, one for the master branch and the other for the dev branch. If you could review and proceed with a new release, it would be nice.

**Comment by GavinPHR** [comment]
This should now be resolved.
