### ISSUE TITLE
Interoperability between dict and TreeMap

### ISSUE THREAD

**Issue by rafaelsilverioit** [GavinPHR/pytreemap#2]
It would be nice if we had a method to convert the TreeMap to a dict and vice versa or a default json serializer/deserializer. Right now I'm trying to figure out how I'm going to do it for my simple use case.

**Comment by GavinPHR** [comment]
I guess you can just iterate through the TreeMap and insert each key-value pair into a dictionary, and vice versa?

**Comment by rafaelsilverioit** [comment]
What a fool I am! Never thought about that. Thank you. haha
